# Generated by Django 5.2.4 on 2025-08-20 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='story',
        ),
        migrations.RemoveField(
            model_name='storyreaction',
            name='story',
        ),
        migrations.RemoveField(
            model_name='storyreaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='story',
            name='tags',
        ),
        migrations.AlterModelOptions(
            name='story',
            options={},
        ),
        migrations.RenameField(
            model_name='story',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='is_featured',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='story',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='story',
            name='category',
        ),
        migrations.RemoveField(
            model_name='story',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='story',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='story',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='story',
            name='status',
        ),
        migrations.RemoveField(
            model_name='story',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='story',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='story',
            name='views',
        ),
        migrations.RemoveField(
            model_name='story',
            name='word_file',
        ),
        migrations.AddField(
            model_name='story',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='story_images/'),
        ),
        migrations.AddField(
            model_name='story',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='StoryReaction',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
