# Generated by Django 5.2.4 on 2025-08-20 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_remove_comment_story_remove_storyreaction_story_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
