# Generated by Django 5.2.4 on 2025-08-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_story_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-published_at', '-created_at']},
        ),
        migrations.RenameField(
            model_name='story',
            old_name='content',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
        migrations.RemoveField(
            model_name='story',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='story',
            name='location',
        ),
        migrations.RemoveField(
            model_name='story',
            name='submitted_by',
        ),
        migrations.AddField(
            model_name='story',
            name='author_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='story',
            name='category',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='story',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='stories/covers/'),
        ),
        migrations.AddField(
            model_name='story',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='story',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='story',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='story',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='story',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='story',
            name='word_file',
            field=models.FileField(blank=True, null=True, upload_to='stories/docs/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='title',
            field=models.CharField(max_length=180),
        ),
    ]
