# Generated by Django 5.2.4 on 2025-07-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('chronic_disease', models.BooleanField()),
                ('infection', models.BooleanField()),
                ('is_eligible', models.BooleanField()),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
