# Generated by Django 5.2.4 on 2025-08-20 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('chronic_disease', models.BooleanField(default=False)),
                ('infection', models.BooleanField(default=False)),
                ('recent_surgery', models.BooleanField(default=False)),
                ('cancer_history', models.BooleanField(default=False)),
                ('substance_abuse', models.BooleanField(default=False)),
                ('pregnant', models.BooleanField(default=False)),
                ('is_eligible', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('transplant_type', models.CharField(blank=True, max_length=100, null=True)),
                ('organ_donation_thoughts', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('selected_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eligibility.hospital')),
            ],
        ),
    ]
