# Generated by Django 5.2.4 on 2025-07-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0002_hospital'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycheck',
            name='cancer_history',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='pregnant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='recent_surgery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='substance_abuse',
            field=models.BooleanField(default=False),
        ),
    ]
