# Generated by Django 5.2.4 on 2025-07-27 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0004_eligibilitycheck_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycheck',
            name='selected_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eligibility.hospital'),
        ),
        migrations.AlterField(
            model_name='eligibilitycheck',
            name='chronic_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eligibilitycheck',
            name='infection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eligibilitycheck',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eligibilitycheck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
