# Generated by Django 5.2.4 on 2025-08-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0005_eligibilitycheck_selected_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibilitycheck',
            name='organ_donation_thoughts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eligibilitycheck',
            name='transplant_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
